# 配置文件

DAILY_TIME: "7:00" # 每日定时发送时间。该时间为系统时间，如果当前系统时间不为北京时间需要自行进行换算

START_DATE: "2023-05-02" # 纪念日
CITY: "宣城"

BIRTHDAY:
  - "04-11"

APP_ID: "wx26ad86a9b3a162a0"
APP_SECRET: "5e034913a62d4aaf232732afc4c1a6cf"

USER_ID: 
  - "ol0Wd54lFUsUzWCvEYh_DfKKZUYA"
TEMPLATE_ID: "WfPtz1YY-bmeCnZ8252ae-DbX8xKq4PbAWtxu80Zozk"
